### ISSUE TITLE
🐛 [bug]: Remove `.venv` from repo

### ISSUE THREAD

**Issue by thekaushikls-infrared** [lsvishaal/Face-Detection-Python#1]
I see that you have pushed the virtual environment to GitHub. While it is good that you share the exact environment, the standard practice is to create and share a `requirements.txt` file instead.

See Reference:
1. [requirements.txt](https://github.com/thekaushikls/Sage/blob/main/requirements.txt)
2. [.gitignore](https://github.com/thekaushikls/Sage/blob/main/.gitignore)

## Steps
1. Activate your venv
```
.venv\Scripts\activate
```
2. Extract requirements
```
pip freeze > requirements.txt
```
3. Add a standard `.gitignore` file for Python from [here](https://raw.githubusercontent.com/github/gitignore/main/Python.gitignore)

**Comment by lsvishaal** [comment]
Done
